baseURL = 'https://krug-klaerungen.de/'
languageCode = 'de-de'
title = 'Krug Klärungen'
theme = 'blist'
accentColor = '#f6ad55'

# Remove multilanguage specific configurations
contentDir = "content"
DefaultContentLanguage = "de"

# Main Menu
[[menu.main]]
name = "Klärungen"
url = "/"
weight = 1

[[menu.main]]
name = "Über mich"
url = "/ueber-mich"
weight = 2

[[menu.main]]
name = "Kontakt"
url = "/anfahrt-kontakt-honorar"
weight = 3

[[menu.main]]
name = "F.A.Q"
url = "/fragen-und-antworten"
weight = 4

[params]
# Enable the darkmode toggle in header
darkModeToggle = false

# Enable search in header
enableSearch = false

# Option to customize the search parameters of a page
searchKeys = [
    "tags",
    "date",
    "categories",
    "summary",
    "content",
    "link",
    "author"
]

# Custom copyright - optional
copyright = "Copyright © 2024 - Tanja Krug · All rights reserved"
favicon = ""

# Color for the intro details and social links block
ascentColor = ""

# Logo and intro photo
introPhoto = "image/logo-krug-klaerungen.png"
logo = "image/logo-krug-klaerungen-header.jpg"

# Used to hide the post metadata such as posted date, reading time and word count
hideMeta = true

# Add support for Table of contents
toc = false

# Hides the thumbnail in post view
hidePageThumbnail = false

[build]
writeStats = true

[outputs]
home = ["HTML", "RSS", "JSON"]

# syntax highlight settings
[markup]
[markup.highlight]
style = "dracula"
[markup.goldmark.renderer]
# Enable to include inline HTML
unsafe = true