baseURL = 'https://musical-capybara-c41cf1.netlify.app/'
languageCode = 'de-de'
title = 'Krug Klärungen'
theme = 'blist'

DefaultContentLanguage = "de"
DefaultContentLanguageInSubdir = true
[languages]
[languages.de]
contentDir = "content/de" # Deutsch
weight = 1
languageName = "Deutsch"
introPhoto = "image/logo-krug-klaerungen.png"
logo = "image/logo-krug-klaerungen-header.jpg"

[[languages.de.menu.main]]
name = "Klärungen"
url = "/"
weight = 1

[[languages.de.menu.main]]
name = "Über mich"
url = "/ueber-mich"
weight = 2

[[languages.de.menu.main]]
name = "Kontakt"
url = "/anfahrt-kontakt-honorar"
weight = 3


[params]
# Enable the darkmode toggle in header
darkModeToggle = false

# Enable search in header
enableSearch = false

# Option to customize the search parameters of a page
# Below are the supported options; Note that including entire content
# may slowdown the loading of search results
# Title of page is included by default
searchKeys = [
    "tags",
    "date",
    "categories",
    "summary",
    "content",
    "link",
    "author"
]

# Custom copyright - optional
copyright = "Copyright © 2024 - Tanja Krug · All rights reserved"
favicon = ""

# Color for the intro details and social links block, not applicable for dark mode
# Supported values: Any color from TailwindCSS default colors
# Reference: https://tailwindcss.com/docs/customizing-colors
ascentColor = ""

# Used to hide the post metadata such as posted date, reading time and word count
# Can be used at site level or page level
hideMeta = true

# Add support for Table of contents
# Can be added to a page level also in markdown frontmatter
toc = false

# Hides the thumbnail in post view
# Thumbnails in home and blog pages will still be shown
# This setting can also be in page's markdown file
hidePageThumbnail = false



[build]
writeStats = true

[outputs]
home = ["HTML", "RSS", "JSON"]

# syntax highlight settings
[markup]
[markup.highlight]
style = "dracula"
[markup.goldmark.renderer]
# Enable to include inline HTML
unsafe = true
