[build]
publish = "public"
command = "git submodule update --init --recursive && hugo --gc --minify"

[build.environment]
HUGO_VERSION = "0.121.2"
HUGO_EXTENDED = "true"

[context.production.environment]
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

# Your other settings remain the same